### ISSUE TITLE
Move to JuliaArrays?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaArrays/LazyArrays.jl#1]
@andreasnoack @andyferris @mbauman

I would like to move this package to JuliaArrays, before someone else makes their own LazyArrays.jl without noticing this one (which is hard to find). Any objections? 

I've added the README which shows the current capabilities.

PS This used to be called LazyLinearAlgebra.jl, but I decided LazyArrays.jl is a more accurate description.

**Comment by andyferris** [comment]
I don't have much opinion on what goes into the organizations (seems OK to me), but regarding your concern

 > before someone else makes their own LazyArrays.jl without noticing this one (which is hard to find)

you can make sure you've registered your package on METADATA, announced it on Discourse, and so-on. (You can move the location of something in METADATA without too much trouble)

**Comment by dlfivefifty** [comment]
Yes of course. Though a lot of times I find packages by looking at what else is in an organisation. Also, I recall someone not knowing about BlockArrays.jl before I asked `@kristofferc` to move it to JuliaArrays.

That said, I don't have access to attobot in JuliaArrays yet (https://github.com/JuliaArrays/BlockArrays.jl/issues/46) and I don't actually know how to do a PR to METADATA for an 0.7 only package, so maybe I'll hold off for now so I can do it using attobot.

**Comment by andyferris** [comment]
Attobot is enabled at the organization level for JuliaArrays, as I understand?

> I don't actually know how to do a PR to METADATA

I believe you can create a REQUIRE file and put `Julia 0.7-` and use attobot like a v0.6 package.

**Comment by dlfivefifty** [comment]
That's what I thought, but it wasn't working in BlockArrays.jl. Maybe it needs to be turned on for that repository? Or maybe I just need to try again.

**Comment by dlfivefifty** [comment]
OK I think I'll move this to JuliaArrays now, and then tag a release.

**Comment by dlfivefifty** [comment]
Ah I don't think I have the ability to move this. @andyferris should I add you as an admin to this package so you can move it?

**Comment by andyferris** [comment]
@dlfivefifty Sorry for the delay. Yes, we can do it that way. Once it's moved I will make sure that you retain admin access to LazyArrays.

**Comment by andyferris** [comment]
Thanks... I think I need an upgrade to admin?

**Comment by dlfivefifty** [comment]
Odd, it looks like I can’t make you an admin, but I can transfer ownership. I’ll try that.

**Comment by andyferris** [comment]
OK I seem to have it now... I'll move it along soon (I'll give github some time first because in case something cached gets broken).

**Comment by andyferris** [comment]
Should be good to go.

Note: I've had trouble with broken CI links before.
