### ISSUE TITLE
Infix operators

### ISSUE THREAD

**Issue by tkf** [JuliaArrays/LazyArrays.jl#10]
As briefly discussed in https://github.com/JuliaArrays/LazyArrays.jl/issues/8#issuecomment-441395949, it'd be nice to have some infix operator for `Mul` and `Add`.

FYI here is the list of infix operators with plus and time precedence (from https://github.com/JuliaLang/julia/blob/master/src/julia-parser.scm):

`(define prec-plus        (append! '($)
                          (add-dots '(+ - |\|| ⊕ ⊖ ⊞ ⊟ |++| ∪ ∨ ⊔ ± ∓ ∔ ∸ ≏ ⊎ ⊻ ⊽ ⋎ ⋓ ⧺ ⧻ ⨈ ⨢ ⨣ ⨤ ⨥ ⨦ ⨧ ⨨ ⨩ ⨪ ⨫ ⨬ ⨭ ⨮ ⨹ ⨺ ⩁ ⩂ ⩅ ⩊ ⩌ ⩏ ⩐ ⩒ ⩔ ⩖ ⩗ ⩛ ⩝ ⩡ ⩢ ⩣))))`

`(define prec-times       (add-dots '(* / ÷ % & ⋅ ∘ × |\\| ∩ ∧ ⊗ ⊘ ⊙ ⊚ ⊛ ⊠ ⊡ ⊓ ∗ ∙ ∤ ⅋ ≀ ⊼ ⋄ ⋆ ⋇ ⋉ ⋊ ⋋ ⋌ ⋏ ⋒ ⟑ ⦸ ⦼ ⦾ ⦿ ⧶ ⧷ ⨇ ⨰ ⨱ ⨲ ⨳ ⨴ ⨵ ⨶ ⨷ ⨸ ⨻ ⨼ ⨽ ⩀ ⩃ ⩄ ⩋ ⩍ ⩎ ⩑ ⩓ ⩕ ⩘ ⩚ ⩜ ⩞ ⩟ ⩠ ⫛ ⊍ ▷ ⨝ ⟕ ⟖ ⟗)))`

We can also add suffixes and combining characters https://github.com/JuliaLang/julia/pull/22089

Some ideas:

- `*″` `+″`: Declare some common suffix to represent lazy version (e.g., double-prime `″`).  It would be handy if we need more operators in the future (e.g, `-″`).

- `*ₗ` `+ₗ`: Same idea but with a subscript `l` (or maybe superscript).

- `*̂` `+̂`: Same idea but with combining character.  It may be hard to recognize in some fonts.

- `⋆`: good for lazy multiplication, as it looks like `*` but sufficiently different to distinguish?

- `⊕`: good for lazy sum as it already has semantics of element wise sum (direct sum)?  But this does not apply to `Mul`.

I think common suffix (like `ₗ` and `″`) is a good choice as it provides a uniform style and it is extensible.

**Comment by tkf** [comment]
Here is a snippet to show `*` and `+` with the combining characters

```julia
for c in '\u0300':'\u036f'
    print("*", c, " ", "+", c, " ")
end
println()
```

Output:

`*̀ +̀ *́ +́ *̂ +̂ *̃ +̃ *̄ +̄ *̅ +̅ *̆ +̆ *̇ +̇ *̈ +̈ *̉ +̉ *̊ +̊ *̋ +̋ *̌ +̌ *̍ +̍ *̎ +̎ *̏ +̏ *̐ +̐ *̑ +̑ *̒ +̒ *̓ +̓ *̔ +̔ *̕ +̕ *̖ +̖ *̗ +̗ *̘ +̘ *̙ +̙ *̚ +̚ *̛ +̛ *̜ +̜ *̝ +̝ *̞ +̞ *̟ +̟ *̠ +̠ *̡ +̡ *̢ +̢ *̣ +̣ *̤ +̤ *̥ +̥ *̦ +̦ *̧ +̧ *̨ +̨ *̩ +̩ *̪ +̪ *̫ +̫ *̬ +̬ *̭ +̭ *̮ +̮ *̯ +̯ *̰ +̰ *̱ +̱ *̲ +̲ *̳ +̳ *̴ +̴ *̵ +̵ *̶ +̶ *̷ +̷ *̸ +̸ *̹ +̹ *̺ +̺ *̻ +̻ *̼ +̼ *̽ +̽ *̾ +̾ *̿ +̿ *̀ +̀ *́ +́ *͂ +͂ *̓ +̓ *̈́ +̈́ *ͅ +ͅ *͆ +͆ *͇ +͇ *͈ +͈ *͉ +͉ *͊ +͊ *͋ +͋ *͌ +͌ *͍ +͍ *͎ +͎ *͏ +͏ *͐ +͐ *͑ +͑ *͒ +͒ *͓ +͓ *͔ +͔ *͕ +͕ *͖ +͖ *͗ +͗ *͘ +͘ *͙ +͙ *͚ +͚ *͛ +͛ *͜ +͜ *͝ +͝ *͞ +͞ *͟ +͟ *͠ +͠ *͡ +͡ *͢ +͢ *ͣ +ͣ *ͤ +ͤ *ͥ +ͥ *ͦ +ͦ *ͧ +ͧ *ͨ +ͨ *ͩ +ͩ *ͪ +ͪ *ͫ +ͫ *ͬ +ͬ *ͭ +ͭ *ͮ +ͮ *ͯ +ͯ`

Here is how it looks in my terminal (using UbuntuMono font in urxvt):

![image](https://user-images.githubusercontent.com/29282/49025375-5a550880-f150-11e8-849f-1b19e076fe34.png)

**Comment by tkf** [comment]
Here is how it is rendered in Emacs with DejaVu Sans Mono:

![image](https://user-images.githubusercontent.com/29282/49026515-e831f300-f152-11e8-94fc-2c05cac2593c.png)

It looks like combining characters going below the symbol (e.g., `*̰ +̰`) are easier to recognize in general.

**Comment by tkf** [comment]
Sadly, `⨴` cannot be rendered in my environment (in browser, terminal and editor).

`⋆` sounds good to me too, but I'd like to have a lazy addition API as well.  How about `⊕`?

**Comment by dlfivefifty** [comment]
I don't know about `⊕`: it means direct sum and I think of it more of a a "block-diagonal" operation, and based on the definition you might expect `(A ⊕ B) * (C ⊕ D) == (A*B) ⊕ (C*D)`, though I suppose if the group operation is `+` then its a different story.

Do we envision other lazy operations? If so, a sub/superscript may be the best. If only subscript `l` rendered for me!

**Comment by tkf** [comment]
Ah, I get what you are saying about `⊕`. Yes, `⊕` would be confusing.

> Do we envision other lazy operations?

Point-wise subtraction could be useful to have.

> If only subscript `l` rendered for me!

How about the superscript?: `*ˡ`

**Comment by tkf** [comment]
> Do we envision other lazy operations?

I think an important question here is if we want to have a lazy Hadamard/elementwise product because then we need two flavors of `*`.  But I can't imagine the situation you'd need it.

**Comment by dlfivefifty** [comment]
> I think an important question here is if we want to have a lazy Hadamard/elem

Remember we always have the explicit `broadcasted(*, A, B)` and `BroadcastArray(*, A, B)` so the unicode are only needed for often used cases. I don't think lazy Hadamard is important enough to warrant a special syntax.

**Comment by tkf** [comment]
I just wanted to point out the naming system that just append a suffix is going to break _if_ we want infix operator for the two flavors of multiplication.  But I agree that's very unlikely.

**Comment by dlfivefifty** [comment]
I think `@~` has superseded this.
