### ISSUE TITLE
CompatHelper has not run for a long time

### ISSUE THREAD

**Issue by jagot** [JuliaArrays/LazyArrays.jl#182]
While looking which packages that are holding back FillArrays 0.12 in a downstream package, I found that CompatHelper has not run here for quite some time:
https://github.com/JuliaArrays/LazyArrays.jl/runs/2995521530?check_suite_focus=true#step:4:7
Possibly this can be alleviated by running on a newer version of Julia than 1.2?

**Comment by dlfivefifty** [comment]
updated
