### ISSUE TITLE
non-broadcasted LazyArray bug?

### ISSUE THREAD

**Issue by jlchan** [JuliaArrays/LazyArrays.jl#189]
I think this is a bug? I get incorrect behavior for a non-broadcasted LazyArray
```julia
julia> a = 1.0; A = randn(10,10); LazyArray(@~ a*A)
(Float64) * (10×10 Matrix{Float64}):
 0.35979  -1.16647  0.969645  -1.55845  0.048995  -1.39117  0.319372  -0.148495  0.95783  0.450661
    ⋅        ⋅         ⋅         ⋅         ⋅         ⋅         ⋅          ⋅         ⋅        ⋅    
    ⋅        ⋅         ⋅         ⋅         ⋅         ⋅         ⋅          ⋅         ⋅        ⋅    
    ⋅        ⋅         ⋅         ⋅         ⋅         ⋅         ⋅          ⋅         ⋅        ⋅    
    ⋅        ⋅         ⋅         ⋅         ⋅         ⋅         ⋅          ⋅         ⋅        ⋅    
    ⋅        ⋅         ⋅         ⋅         ⋅         ⋅         ⋅          ⋅         ⋅        ⋅    
    ⋅        ⋅         ⋅         ⋅         ⋅         ⋅         ⋅          ⋅         ⋅        ⋅    
    ⋅        ⋅         ⋅         ⋅         ⋅         ⋅         ⋅          ⋅         ⋅        ⋅    
    ⋅        ⋅         ⋅         ⋅         ⋅         ⋅         ⋅          ⋅         ⋅        ⋅    
    ⋅        ⋅         ⋅         ⋅         ⋅         ⋅         ⋅          ⋅         ⋅        ⋅    
julia> norm(LazyArray(@~ a*A) - a*A)
12.084738419083282
```
However, `Matrix(LazyArray(@~ a*A))` returns the correct result.
```julia
julia> norm(Matrix(LazyArray(@~ a*A)) - a*A)
0.0
```

**Comment by dlfivefifty** [comment]
I think the issue is that it is using the size of the first argument to determine the ` colsupport ` , and is unaware of the scalar special case

can you use ` BroadcastArray ` instead?

**Comment by jlchan** [comment]
Thanks for the explanation. I was using `BroadcastArray`, but that seemed to result in a lot of time being spent in `lazybroadasting.jl` https://github.com/trixi-framework/Trixi.jl/pull/757#issuecomment-892157256. I probably need to look a little more closely at the ProfileView details though.

**Comment by dlfivefifty** [comment]
Can you give a MWE of what you are trying to do that is slow?

Note that one should never call `getindex` on a lazy array as it will be slow. But if you use `copyto!` it should be fast, e.g.
```julia
julia> a = BroadcastArray(*, 5, randn(100));

julia> n = 100; @time copyto!(Vector{Float64}(undef, n), view(a,1:n));
  0.000012 seconds (3 allocations: 992 bytes)
```

**Comment by jlchan** [comment]
Sure - here's an example:

```julia
using LazyArrays
using StructArrays

n = 100
u = randn(n)
du = similar(u)
A, B, C, D = ntuple(_ -> randn(n, n), 4)
Alazy = LazyArray(@~ @. C[1,1] * A + D[1,1] * B)

# some random function
@inline f(x, y) = log(.5 * (exp(x) + exp(y)))

function foo_lazy!(du, u, A, f)
  rows, cols = axes(A)
  for i in rows, j in cols
    AFij = A[i,j] * f(u[i], u[j])
    du[i] = du[i] + AFij
  end
end
function foo!(du, u, A, B, C, D, f)
  rows, cols = axes(A)
  for i in rows, j in cols
    Aij = C[1,1] * A[i,j] + D[1,1] * B[i,j]
    AFij = Aij * f(u[i], u[j])
    du[i] = du[i] + AFij
  end
end
```
The timing I get is
```julia
julia> @btime foo!($du, $u, $A, $B, $C, $D, $f)
  216.557 μs (0 allocations: 0 bytes)

julia> @btime foo_lazy!($du, $u, $Alazy, $f)
  306.281 μs (0 allocations: 0 bytes)
```
The ProfileView of `foo!` is here:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/1156048/128382383-7ba8e6a0-eaa8-4e8f-9dfe-7db9f4ed5775.png">

while the ProfileView of `foo_lazy!` shows some overhead in `lazybroadcasting.jl`. 
<img width="912" alt="image" src="https://user-images.githubusercontent.com/1156048/128382372-8a18684f-01a2-4887-bb53-11891e8ed15b.png">

Is this related to your comment on `getindex`?

**Comment by dlfivefifty** [comment]
Yes you are using ` getindex ` (` A[i,j] `) so it’s going to be slow. Writing it as matrix multiplication should be faster

**Comment by jlchan** [comment]
Gotcha. Thanks for the tip!
