### ISSUE TITLE
Downstream testing for InfiniteLinearAlgebra.jl

### ISSUE THREAD

**Issue by DanielVandH** [JuliaArrays/LazyArrays.jl#314]
https://github.com/JuliaArrays/LazyArrays.jl/blob/052a0f6cd85911951b3ec6a6b6030420926d70f6/.github/workflows/downstream.yml#L34

Does this still need to be commented out?

**Comment by dlfivefifty** [comment]
Oh forgot this was commented out. Yes we can turn the tests back on
