### ISSUE TITLE
Performance improvement of Kron times Vector/Matrix

### ISSUE THREAD

**Issue by martka** [JuliaArrays/LazyArrays.jl#65]
Up to now I was using v0.9.1 of LazyArrays and implemented an improved version of multiplying a Kron with a Vector/Matrix. After updating to v0.12.0 my code is not working 
anymore.

I'm writing a program for statistical analysis of data that makes heavy use of big matrices.
The memory requirement of the matrices that I'm using can easily go up to 100TB, way too big to store them directly in memory. Luckily my matrices are kronecker products of smaller matrices so i am using LazyArrays.Kron to represent them.

In my program i often need to multiply a Kron with a Vector or Matrix. Up to now i was using version 0.9.1 of LazyArrays and the way the multiplication is carried out there is not feasible for me (IIRC generic_matmatmul gets called and each element of the Kron is visited individually).

Therefore, I implemented my own version of `(*)(::Kron,::Vector)` or actually `mul!(::Vector, ::Kron, ::Vector)`. 
In essence it uses the property `Kron(A,B)*vec(X)=vec(B*X*A^T)` ([https://en.wikipedia.org/wiki/Kronecker_product#Matrix_equations](url)) to avoid creating a dense matrix and iterating through all elements of the matrix. If a matrix should be multiplied it does so by multiplying for each column using views of the columns to avoid memory allocation. Higher order kronecker products are handled recursively `Kron(A,B,C)*vec(X)=Kron(B,C)*(X*A^T)`. The actual implementation is of course a bit more complicated, especially for higher order kronecker products where chains of reshape/view occur (the BLAS functions don't like chains of reshape/view).
I was able to achieve a significant performance improvement w.r.t. the 0.9.1 version of LazyArrays and also the straigh-forward Julia implementation using `kron`(not for the huge matrices of course).
```
A=randn(ComplexF64,10,10);
B=randn(ComplexF64,10,10);
C=kron(A,B);
CK=Kron(A,B);
x=randn(size(CK,1));
C*x;CK*x; # warmup
@btime $CK*$x; #  6.861 μs (10 allocations: 6.88 KiB)
@btime $C*$x; #   21.639 μs (1 allocation: 3.25 KiB)
```
Please note that the benchmark for `kron` does not take into account the time it takes to compute `kron(A,B)` and still it performs worse. For higher order kronecker products the performance gain differs but is there and allows me to work with big matrices at all.

Without any changes to v0.9.1 i got this result
```
@btime $CK*$x; #  1.291 ms (1 allocation: 3.25 KiB)
``` 

Now for my actual question. I was updating LazyArrays from 0.9.1 to 0.12.0 and the way i implemented my improvement is not working anymore (my own version of `mul!`is not called anymore) and i'm wondering now what is the best place in the source code for my improvement. 
I do not fully understand all the changes from 0.9.1 to 0.12.0, all i could figure out for now is that ultimately `default_blasmul!` is called. Would that be an appropriate spot for my changes? Could i just implement a version of `default_blasmul!` that specializes on `Kron` or would that interfere with `apply, applied, ApplArray` or in general with the way multiplication is carried out in 0.12.0?

Thank you for any hints
BR
Martin 

PS: unfortunately i couldn't find the time in the past to clean-up my code and provide the improvements already for v0.9.1 but maybe it can be done now

**Comment by dlfivefifty** [comment]
LazyArrays replicates the broadcast design to avoid the “broken” ` mul! ` framework. Essentially multiplication becomes
```Julia
materialize(applied(*, A, B)) 
```
allowing for ` ApplyStyle ` to specify how it’s materialize. It defaults to ` MulAddStyle ` and then in-place multiplication becomes
```Julia
materialize!(MulAdd(1.0, A, B, 0.0, C)) 
```
This uses ` MemoryLayout ` to determine how to materialize the ` MulAdd `. Probably you want to overload
```Julia
function materialize!(::MatMulVecAdd{ApplyLayout{typeof(kron)}})
```

**Comment by martka** [comment]
> Probably you want to overload
> 
> ```julia
> function materialize!(::MatMulVecAdd{ApplyLayout{typeof(kron)}})
> ```

Thanks for your quick reply. I will have a look at it.

**Comment by emerali** [comment]
Would it be possible to get this added to the official package? It would be quite useful.

I could also help out with implementing the case where the number of Kronecker factors is greater than 2 ([ref](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.379.9338&rep=rep1&type=pdf) see algorithm 2) since using the current recursive approach to larger kronecker products likely won't scale too well.

**Comment by dlfivefifty** [comment]
If you make a PR that would be great! I don’t have time to do this myself at the moment.

**Comment by emerali** [comment]
alrighty then
