### ISSUE TITLE
Why isn't `AddArray` a `BroadcastArray`?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaArrays/LazyArrays.jl#71]
@tkf I think I changed `AddArray` at some point to be an `ApplyArray`. But in retrospect it could have also been a `BroadcastArray`. Do you have a feeling if one is better?

Here are the pros/cons I can think of:

1. `BroadcastArray` is more general, and is more "fundamental" in the sense that `A + B` calls `A .+ B`
2. `ApplyArray` has the extra information that all the arguments are the same size, which simplifies the implementation of `materialize!`

In terms of implementation, if we prefer `BroadcastArray` we could introduce a `BroadcastArrayApplyStyle` and have:
```julia
applied(::BroadcastArrayApplyStyle, f, A...) = broadcasted(f, A...)
```
(Actually, I just realized `applied(::AppleStyle, f, A...)` should be added to more closely match `broadcasted`)

**Comment by dlfivefifty** [comment]
Here's an idea: support both! We can convert between the two representations via:
```julia
# Any ApplyArray _is_ a BroadcastArray
BroadcastArray(A::ApplyArray{<:Any,typeof(+)}) = BroadcastArray(+, A.args...)
# A BroadcastArray _is_ an ApplyArray with the right axes
function _broadcast_resize(A, (m,n)) 
   if size(A,1) == 1 
       ApplyArray(*, Ones(m), A)
    elseif size(A,2) == 1
       ApplyArray(*, A, Ones(1,m))
    else
       A
    end
end
ApplyArray(A::BroadcastMatrix{<:Any,typeof(+)}) = BroadcastArray(+, _broadcast_resize.(A.args, Ref(size(A)))
```

The one catch is it's not type stable...perhaps instead of converting we do that in the materialize stage:
```julia
        function materialize!(M::$MulAdd_{BroadcastLayout{typeof(+)}})
            α, A, B, β, C = M.α, M.A, M.B, M.β, M.C
            m,n = size(A)
            if C ≡ B
                B = copy(B)
            end
            _fill_lmul!(β, C)
            for a in arguments(A)
                 if size(a,1) == 1
                       C .= applied(+,applied(*,α,Ones(m),a,B), C)                 
                 elseif size(a,2) == 1
                        C .= applied(+,applied(*,α,a,Ones(1,m),B), C)                 
                 else
                       C .= applied(+,applied(*,α, a,B), C)
                  end
            end
            C
        end
```

**Comment by tkf** [comment]
Another benefit for `ApplyArray` is that `A + I` (`A :: AbstractMatrix`, `I :: UniformScaling`) works (although it may be supported at some point https://github.com/JuliaLang/julia/issues/23197).

> Here's an idea: support both!

That sounds great. I think normalizing the representation during `materialize!` is the way to go.
