### ISSUE TITLE
copy of LazyArrays

### ISSUE THREAD

**Issue by tlienart** [JuliaArrays/LazyArrays.jl#85]
Long story short, the copy mechanism of apply arrays seems to cause issues in some problems, suggested alternative below. 

context for this issue:  https://github.com/JuliaData/Tables.jl/issues/122 in particular reproducing MWE  https://github.com/JuliaData/Tables.jl/issues/122#issuecomment-559566278

The problem identified by  @nalimilan is:

> AFAICT, the bug is that `copy(A::ApplyArray) = ApplyArray(A.f, map(copy,A.args)...)` when it should be `copy(A::ApplyArray{T,N}) where {T,N} = ApplyArray{T,N}(A.f, map(copy,A.args)...)`. There may be other places with the same problem.

thoughts?

**Comment by dlfivefifty** [comment]
You are right: ` N ` cannot necessarily be determined automatically so should be part of the ` copy ` . Can you make a PR?

**Comment by tlienart** [comment]
Yes will do
